// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmualcoqyztvtsqhjlzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdWFsY29xeXp0dnRzcWhqbHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDg4NjIsImV4cCI6MjA2NjQyNDg2Mn0.qQxh6IPHrvDQ5Jsma42eHpRTjeG9vpa0rIkErPeCJe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);